from dependencias.Agentes.Base_Agent import *
from dependencias.Agentes.Chaser import *
from dependencias.Agentes.Random_Angent import *
from dependencias.Agentes.Avoid_inmediate_death import *
from dependencias.Agentes.Combined_Heuristic_Agent import *
from dependencias.Agentes.Busqueda_anchura import *
from dependencias.Agentes.deep_q_agent import *
from dependencias.Agentes.deep_q_agent_cnn import *
from dependencias.Agentes.deep_q_agent_8_neurons import *